### ISSUE TITLE
Instructor Feedback - Week 4 Exercise

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Assoman/UsedComputersWebSite#1]
Good work! One question:

- [x] Will you need to search users by any fields other than last name? https://github.com/Assoman/UsedComputersWebSite/blob/0b0e668322b2e3ac381f66919e9da293b3f93bcc/src/main/java/persistence/UserDao.java#L24. If so, you may want to replace this method with one that searches by any property and value (I provided some demo code for this here: https://github.com/MadJavaEntJavaSpring2018/week-1-user-display-exercise-pawaitemadisoncollege/blob/65bff916c112f9f814b97ba15a543319164a0cfb/src/main/java/edu/matc/persistence/UserDao.java#L141).

**Comment by Assoman** [comment]
I've added this method to the UserDao.
