### ISSUE TITLE
Instructor Feedback Week 5

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Assoman/UsedComputersWebSite#2]
Nice job getting that generic dao set up and the one-to-many associations complete.
- [x] Review the week 5 follow up video about .equals and be sure to override .equals in each of your entities. That will allow you to more robustly check the expected entities equal the actual entities in your unit tests - essentially you'll be able to check every instance variable value with a single assertion.
- [x] Once you've updated and verified each of your current DaoTests work using the generic dao, you should be able to get rid of the UserDao and ProductDao. AND you won't need to write any new daos for the rest of your project.

**Comment by Assoman** [comment]
Issues solved.
