### ISSUE TITLE
Holli's Feedback - Peer Review 1

### ISSUE THREAD

**Issue by HolliNiesen** [Assoman/UsedComputersWebSite#3]
# Design/Code Review 1

### Reviewer: Holli

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Explained out loud, the problem statement sounds great!<br>The written version could use an explanation for why you would like to create this site.<br>The functionality and technology section could be more specific. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Design looks straightforward and easy to follow.<br>Design could use some navigation to be able to find account info/ login options from all screens.<br>Could include a way to view products by zip code without an account. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Database design looks good!<br>The approved column could be changed to a boolean, since the design is intended to only include two options.<br>The products table might benefit from a "year" column relating to the year a computer was released. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | Variable names are nice and specific.<br>Code is easy to read.<br>Generic DAO has a searchByLastName method that doesn't really fit if it's truly generic.<br>The tests could be updated to use the generic DAO instead of the user and product DAOs.

**Comment by Assoman** [comment]
Thank you for your comments. Issued solved in my project.
