### ISSUE TITLE
Design review feedback

### ISSUE THREAD

**Issue by jacquesmatcgithub** [Assoman/UsedComputersWebSite#4]
# Design/Code Review 1

### Reviewer: Jacques Fourie

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| The problem statement needs a bit of work, but during the code review it was aparent that you had put a lot of thought into what you want your project to do, so you just need to get that into the problem statement. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | I found your screen design very easy to follow, but just like my design you are obviously still refining what it will look like. Good job on explaining the flow very well. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| I think your datbase design was in the early stage of planning, but what you demonstrated aligned well with your screen designs. You satisfied the one-to-many requirement, and I liked the 'uncluttered' approach you are using in both your screen and database disign. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | We did not get too deeply into your code because of time constraints but I did notice you are using a proper Maven project structure.

**Comment by pawaitemadisoncollege** [comment]
Did you guys check for System.out.println statements?

**Comment by Assoman** [comment]
Thank you for the comments.
