### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by nicolesteck** [Assoman/UsedComputersWebSite#5]
# Design/Code Review 3

#### Reviewer: Nicole Steck

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| |
||Which planned functionality has been met? | All planned functionality has been met. |
|| What planned functionality has not been met? ||
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| Commits multiple times a week, nearly every week, particularly after about week 3. Consistent work effort, no procrastinating. |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.| All feedback has been incorporated, including adding more generic methods and ensuring no print lines are used. |
||Other comments/notes?| |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| The JSPs look wonderful -- very professional, even when they are combining data from multiple places.|
||Other comments/notes?| |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation |No errors found -- remarkably clean project in terms of 'quality' issues. Those issues that remain are not true problems (ie T cast to T), so no true errors or problems remain. | | 
||Other comments/notes?| Great looking page. |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy|Logging looks good. |
||Other comments/notes?| |
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After
||Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| No red flags, authentication looks great and includes logout functionality. |
||Is it implemented correctly and working locally as well as on AWS?
|Working correctly locally, ran out of time to check up on AWS. |Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?| Geocoding API -- works well. |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| |
||Is the independent research topic/technique implemented in the project?| |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?| |
||Is the hosted application fully functioning?| |
||Other comments/notes?| |

**Comment by Assoman** [comment]
Thank you, Nicole.
